title: Notebook
description: Various notes, plans, and ideas.
favicon_ico: "/assets/images/favicon.ico"

remote_theme: just-the-docs/just-the-docs

baseurl: "/notebook"

plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at

color_scheme: dark
enable_dark_mode: true

# Edit this page link
gh_edit_link: true
gh_edit_link_text: "Edit on Github"
gh_edit_repository: "https://github.com/raycadle/notebook"
gh_edit_branch: "main"
gh_edit_source: "."
gh_edit_view_mode: "tree"

# Enable last modified footer timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
